### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Pechi77** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#12]
how to send messages to whatsapp numbers other than my contacts

**Comment by VISWESWARAN1998** [comment]
You cannot send it. But you can add the numbers to your whatsapp and could send it.

**Comment by Pechi77** [comment]
can you add those numbers from this script?
I dont think we can..

**Comment by VISWESWARAN1998** [comment]
There are various way to add numbers to your contacts in bulk, that wont be a problem. This script is just an automation for whatsapp
