### ISSUE TITLE
XPATH Error

### ISSUE THREAD

**Issue by wolkix3** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#13]
Code I use:
`from whatsapp import WhatsApp
whatsapp = WhatsApp(10)
print(whatsapp.get_last_seen("Max"))`
I'm trying to get the last seen of somebody but I always get this error:

`Exception has occurred: selenium.common.exceptions.TimeoutException
Message:  
  File "C:\Users\Thore\Desktop\WA Track\whatsapp.py", line 44, in __init__
    (By.XPATH, '//*[@id="side"]/div[2]/div/label/input')))
  File "C:\Users\Thore\Desktop\WA Track\tracker.py", line 2, in <module>
    whatsapp = WhatsApp(10)`

**Comment by VISWESWARAN1998** [comment]
This works for me..

```
# SWAMI KARUPPASWAMI THUNNAI

from whatsapp import WhatsApp

app = WhatsApp(1000)
seen = app.get_last_seen("Thamarai")
print(seen)

```

**Comment by VISWESWARAN1998** [comment]
@wolkix3 

`whatsapp = WhatsApp(10)`

I see the above line in your code, so the application will wait only for 10 seconds. i.e you can only 10 seconds to scan your qr code. So why you get timeout exception.

This will wait for 1000 seconds, may be you could try it.

`app = WhatsApp(1000)`

**Comment by wolkix3** [comment]
I do in the time scan the qr code and get logged into WhatsApp Web, but I still do get the same error as soon the time runs out.

**Comment by VISWESWARAN1998** [comment]
@wolkix3 Have you changed the value to greater than 1000 and tried?

**Comment by wolkix3** [comment]
Okay setting it to 2000 helped somehow, thank you
