### ISSUE TITLE
Timeout error when trying getting the last seen of a invisible.

### ISSUE THREAD

**Issue by wolkix3** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#14]
I'm trying to get the last seen from somebody that has their settings like set so only it is seen when they are online but not their last seen. But if they are online I'm getting the Error `TimeoutError: Your request has been timed out! Try overriding timeout!`. And now I'm asking how do I override this error and just basically wait till they come online and then get their last seen status aka the Online Status?

**Comment by wolkix3** [comment]
I know that it outputs if it doesn't find any as None, but now I'm getting the TimeoutError

**Comment by VISWESWARAN1998** [comment]
Loop untill they come online on a separate thread???

**Comment by VISWESWARAN1998** [comment]
> I'm trying to get the last seen from somebody that has their settings like set so only it is seen when they are online

So in that case, the whats-app will display online only when they come online, so you could use a loop like this to see whether they came online or not. Example program below

```
# SWAMI KARUPPASWAMI THUNNAI

from whatsapp import WhatsApp
import time
from threading import Thread


def came_online(person_name, app):
    while True:
        try:
            status = app.get_last_seen(person_name)
            if status == "online":
                print("Came online")
            else:
                print(status)
        except TimeoutException:
            print("Not Came online")
        time.sleep(1) # Hold on for a second
        

app = WhatsApp(1000)
thread = Thread(target=came_online, args=("Amma", app))
thread.start()
```

**OUTPUT:**
```
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
last seen today at 10:46 AM
Came online
Came online
Came online
Came online
```

Even if you put it in a separate thread that will affect other process like creating groups, sending messages etc., In that case you need to use Locks to make sure everything is synchronized.

Thank you for using my API.

Regards,
Visweswaran N

**Comment by wolkix3** [comment]
I already got it to work when they are like they show the last seen, but when it is hidden, even with your code I do get online one `None` output and then an error that TimeoutException is not defined. And if I add `class TimeoutException(Exception): pass` at the start to pass it, I do then get the `TimeoutError: Your request has been timed out! Try overriding timeout!` again.

**Comment by wolkix3** [comment]
Okay, thank you a lot this fixes the error. Now I got one last question, it only gives out one time the `None` and then again, Now I'm asking if the Person is gonna go online, will it then output the new online status then or is it just never gonna check it again?

**Comment by VISWESWARAN1998** [comment]
@wolkix3 
It is an API, you can make it to check online status of a person on a regular interval using some looping mechanism.

**Comment by VISWESWARAN1998** [comment]
Like this: https://github.com/VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api/issues/14#issuecomment-429598975

**Comment by wolkix3** [comment]
My question was only because it only outputs the None once if it even still checks it. But now I checked it and it is working as intended. I really need to thank you so much for all your help!
