### ISSUE TITLE
Read messages

### ISSUE THREAD

**Issue by MareinK** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#17]
I'd like to read messages by others (in a group chat) and respond depending on the message. This doesn't seem possible at present. It would be great if it would be possible to read messages from chats!

**Comment by VISWESWARAN1998** [comment]
Did you mean you want to read the last message from other is a group chat?

Or if you want to check if a message is present in a group, there is already a function in the latest commit.

```python
# SWAMI KARUPPASWAMI THUNNAI

from whatsapp import WhatsApp

app = WhatsApp(100)
PERSON_NAME = "PERSON_NAME"
is_present = app.is_message_present(PERSON_NAME, "Wingardium Leviosa")
if is_present:
    app.send_message(PERSON_NAME, "Up you fly!!!")
else:
    app.send_message(PERSON_NAME, "Wingardium Leviosa")
```

Could you brief your purpose, if it seems to be useful for other community members too, I will try my level best to add it.

Thank you and Regards,
Visweswaran Nagasivam

**Comment by MareinK** [comment]
Thanks for your response. I didn't know about the functionality you show. However I don't think it quite fits my use case. What I'm thinking of is more along these lines:

```python
from whatsapp import WhatsApp

app = WhatsApp(100)
PERSON_NAME = "PERSON_NAME"

def listener(message):
    app.send_message(PERSON_NAME, "You just said: " + message)

app.listen(PERSON_NAME, listener)
```

Of course the actual use case would be something more complicated than just echoing the person's message back to them. But the point is, to listen for new messages, and to be able to execute a function for each new message.

Another alternative would be to get all messages in a chat:

```python
from whatsapp import WhatsApp

app = WhatsApp(100)
PERSON_NAME = "PERSON_NAME"

for message in app.get_all_messages(PERSON_NAME):
    # do something with message
```

They're slightly different use cases but both very useful in my opinion.

**Comment by VISWESWARAN1998** [comment]
You can achieve it with a few tweaks using the latest method.. See unread usernames
