### ISSUE TITLE
How to send image?

### ISSUE THREAD

**Issue by LevisKimathi** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#19]
Hi I'm trying to send image with this code. I'm new to python where I'm I going wrong. It opens chrome browser and asks for qr code confirmation. After confirmation It searches for the Name and opens a chat then it stops there.

from whatsapp import WhatsApp
whatsapp = WhatsApp(20)
whatsapp.send_picture("Name","C:/Users/Levis/Desktop/Images/python.png","Image send test")

**Comment by VISWESWARAN1998** [comment]
Sorry for the late reply,

Have fixed several things and here is how to send the message:

```python
app.send_picture("Vignesh", os.getcwd()+"/pic.jpg")
```

Please make sure you have current updated code!

Thank you,
Visweswaran N

**Comment by LevisKimathi** [comment]
Awesome.Thank you for getting back to me.

**Comment by VISWESWARAN1998** [comment]
Welcome! If you are facing any problems feel free to open new issue.
