### ISSUE TITLE
How to add caption to an image?

### ISSUE THREAD

**Issue by LevisKimathi** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#20]
I can send an image. I wanted to know how to add a caption?

**Comment by VISWESWARAN1998** [comment]
I have just added caption support. Please use the latest whatsapp.py

Here is how you send the caption,

```python
# SWAMI KARUPPASWAMI THUNNAI

from whatsapp import WhatsApp
import time
import os

app = WhatsApp(100)
app.send_picture("Thamarai", os.path.join(os.getcwd(), "Screenshot (747).png"), "Some caption")

```

Thank you!

**Comment by VISWESWARAN1998** [comment]
@LevisKimathi  Do you still face this issue? If not kindly consider closing the issue.

Thank you!
Regards,
Visweswaran N

**Comment by LevisKimathi** [comment]
Thanks you it's working
