### ISSUE TITLE
Error "init (By.CSS_SELECTOR, '.jN-F5')))"

### ISSUE THREAD

**Issue by axyello** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#26]
Hi,
I executed the program, it is the error message obtained.
The browser gets good web.whatsapp and the error is coming up.

C:\Python37\python.exe C:/Wp/Simple/main.py
Traceback (most recent call last):
  File "C:/Wp/Simple/main.py", line 6, in <module>
    app = WhatsApp(10)
  File "C:\Wp\Simple\whatsapp.py", line 51, in __init__
    (By.CSS_SELECTOR, '.jN-F5')))
  File "C:\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Process finished with exit code 1

Thank you.

**Comment by VISWESWARAN1998** [comment]
Good Morning,
    Thank you for raising this issue. It seems that the CSS selectors have been changed. I have fixed the CSS selectors. Download the latest whatsapp.py. 

I have tested with some commonly used methods and it seems to be working.

```python
# SWAMI KARUPPASWAMI THUNNAI

import time
import os
from whatsapp import WhatsApp

name = "Thamarai"

whatsapp = WhatsApp(100)
# Testing Plain message
whatsapp.send_message(name, "Bot Testing - Regular message")
# Testing blind message
for i in range(10):
    whatsapp.send_blind_message("Hello World")
# Testing picture
whatsapp.send_picture(name, os.getcwd()+"/pic.png")
Last seen
print(whatsapp.get_last_seen(name))
print(whatsapp.participants_count_for_group("The Night Ghost Company"))

```
