### ISSUE TITLE
Need an option to clear messages in group

### ISSUE THREAD

**Issue by rajasekar-addobyte** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#27]
First thanks for the code.

I am looking for an option to clear messages in my groups. Can you help me on this?

**Comment by VISWESWARAN1998** [comment]
First of all apologies for the late reply. I have added this feature, Kindly pull the repository or re-download the latest whatsapp.py

*Usage:*

```python
from whatsapp import WhatsApp

whatsapp = WhatsApp(100)
whatsapp.clear_chat("F1 Group")
````

Thank you and regards,
Visweswaran N

**Comment by VISWESWARAN1998** [comment]
@rajasekar-addobyte Kindly close the issue if it has solved your problem.

**Comment by rajasekar-addobyte** [comment]
Thanks for the update. It works. i used it to clear multiple groups

```
from whatsapp import WhatsApp
import time

whatsapp = WhatsApp(100)

participants = ['Group1', 'Group2']


for participant in participants:
    print("Sending: ", participant)
    time.sleep(1)
    try:
        whatsapp.clear_chat(participant.strip())
    except Exception as e:
        print(e)
       
    time.sleep(2)
    whatsapp.goto_main()
```
