### ISSUE TITLE
In Case Number is not a Vaild Whatsapp User

### ISSUE THREAD

**Issue by ankursinghagra** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#28]
Your Script runs great . 
I am having a bit of a issue while sending bulk messages, if the phone number is not a valid whatsapp user, and i am executing send_anon_message() , it breaks. I was hoping it skips that number and move onto the next line.

**Comment by suryabtps** [comment]
Try:
    Function
Except:
    Pass

**Comment by ankursinghagra** [comment]
why didn't i thought of that. Thanks, this works.

**Comment by suryabtps** [comment]
It happens because of monotonous work. Take a break. :)

Warm Regards,
Surya K. S.

**Comment by VISWESWARAN1998** [comment]
@ankursinghagra 

Please note that, WhatsApp will ban your which sends messages to others(who didn't store your phone number)

The limit is 100 I believe.

**Comment by ankursinghagra** [comment]
@VISWESWARAN1998 

Too late . I already go banned.

**Comment by VISWESWARAN1998** [comment]
@ankursinghagra I am sorry to hear that it has nothing to do with API, whats-app bans numbers which sends messages to numbers which are not in the contact list(receiver). I informed you in the same day. 
I do apologize.

**Comment by ankursinghagra** [comment]
@VISWESWARAN1998 
Dont worry. I know its not your api 's fault. Your scripts work well. I was already aware that whatsapp might take actions against spamming, so i used a disposable phone number. ;)
