### ISSUE TITLE
Whatsapp search box element name change and behaviour change

### ISSUE THREAD

**Issue by alexanghh** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#35]
The code is no longer working due to recent Whatsapp changes:
- Element name changed from _2zCfw to _3u328
- Behaviour changed where search text box does not respond to enter to open up the chat. Need to click on the object of the first search result element "_2WP9Q" (first result element is always _2WP9Q)

```
search = self.browser.find_element_by_css_selector("._3u328")
search.send_keys(name+Keys.ENTER) 
chat = self.browser.find_element_by_css_selector("._2WP9Q")
chat.click()
```

**Comment by VISWESWARAN1998** [comment]
Thank you for your contribution, could you send a pull request?

**Comment by VISWESWARAN1998** [comment]
Bug has been fixed with credits on commit name.

Thank you,
Visweswaran N
