### ISSUE TITLE
Runner not found

### ISSUE THREAD

**Issue by alfian8787** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#38]
[](https://github.com/VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api/issues/38#issue-589921636url)

**Comment by alfian8787** [comment]
@VISWESWARAN1998 @VigneshSP94 @cristianlivella @cristianlivella

**Comment by alfian8787** [comment]
https://github.com/VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api/issues/38#issue-589921636 @alfian8787 @gccallie

**Comment by VigneshSP94** [comment]
@cristianlivella can you post some traceback or a description?
