### ISSUE TITLE
error

### ISSUE THREAD

**Issue by boinaweb** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#43]
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=81.0.4044.138)

**Comment by VISWESWARAN1998** [comment]
Could you show me the code which caused this error?

**Comment by boinaweb** [comment]
try:
           WebDriverWait(self.browser, self.timeout).until(EC.presence_of_element_located((By.XPATH, "/html/body/div[1]/div/div/div[2]/div[3]/span/div/div/div[2]/div/div/div/div/div[1]/div/div/div/div[2]/div[1]/span/span/span")))
           return True
        except TimeoutException:
            return False

**Comment by boinaweb** [comment]
All false error messages

**Comment by boinaweb** [comment]
correct code:
/html/body/div[1]/div/div/div[2]/div[3]/span/div/div/div[2]/div/div/div/div[1]/div/div/div/div[2]/div[1]/span/span/span

found the error thanks was just one more div

**Comment by bhavya32** [comment]
@VISWESWARAN1998  why not close the issue?

**Comment by VISWESWARAN1998** [comment]
@bhavya32 Thank you for the remainder!

Regards,
Visweswaran N
