### ISSUE TITLE
Find input bar by ID not working

### ISSUE THREAD

**Issue by gccallie** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#5]
I tried to use your API but the input bar in WhatsApp web can't be accessed via `browser.get_element_by_id` since the id is not available (at least not anymore). Therefore I updated it with `browser.get_element_by_xpath` followed by the input search bar XPATH. 

example (line 42):
`WebDriverWait(self.browser,wait).until(EC.presence_of_element_located(
            (By.XPATH, '//*[@id="side"]/div[2]/div/label/input')))`

**Comment by VISWESWARAN1998** [comment]
@gccallie 
Could you send a Pull Request please! Thanks
