### ISSUE TITLE
[enhancement]emojify is making the program slower

### ISSUE THREAD

**Issue by aahnik** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#52]
# is emojify actually needed?
### I commented out emojify and related lines then

# __this piece of code__
```python
from whatsapp import WhatsApp

wapp = WhatsApp(100, session='aahnik')

msg = """ *Hi Demo Emoji and Formatting*
:-) i am a smiling face *i am a bold text*

_i am italicised lorem ipsum_ 

~strike through message~

;-) i am winking  <3 love is pure
(y) cheers :-p tounge out :-( i am unhappy 

        *MORE EMOJIS*
:-) ;-) (y) 
*It works* Bye """

wapp.send_message('Aahnik Personal', msg)
```

# produced this output
![emoji_demo](https://user-images.githubusercontent.com/66209958/86576307-2e3d7280-bf96-11ea-8238-4a13cd99046e.png)

**Comment by aahnik** [comment]
# removing emojify makes program fast 
# the time difference is considerable when sending 100s of messages

**Comment by VISWESWARAN1998** [comment]
Yes I too had a thought of removing it, which I will remove it in my next commit.

Thank you and Regards,
Visweswaran N

**Comment by aahnik** [comment]
#53 i have removed emojify and updated some sections of readme
 also added many enhancements and new features 
## please review and merge them

## thanks
Aahnik
