### ISSUE TITLE
[feature request] please consider these issues

### ISSUE THREAD

**Issue by aahnik** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#54]
1. Adding delete chat feature.(not same as clear chat)

2. Feature to create whatsapp brodcast lists and delete them

3. Seperate the functionality into different modules.(maintaining the code is difficult as everything is in same file )

4. Xpath and css selector portions must be seperated from code and be hosted in a CDN .( Atleast kept in a seperate var.py file or a json file , so it's easy to modify)

5. A test module to test whether all features of  api is working properly or not. And print exactly  where the api is breaking.

6. Pack all  the modules into a package and adding init.py and setup.py so we can pip install the api in entire system

7. Issue 48 is solved only in method send_message
The issue exists in send_picture and send_document

8. The path of chrome driver installation and the json file containing the latest xpath&css selector should be passed to the constructor . So that the api works in a hassle free manner across.

**Thanks a ton** 🙂
Aahnik

**Comment by aahnik** [comment]
# I could solve most of the above mentioned issues.
I will start working on them after 19th July .
(I have some upcoming exams to prepare for)
## Meanwhile others improve this fantastic api

**Comment by bhavya32** [comment]
Hey @aahnik I want to add a very important feature request.(for me it is important.) Documents can be big or small. If the document is too big, the selenium will close before the file is uploaded. If we increase the time, the next file may be small and it will waste time. We should together sort this issue. There must be some workaround to check if the message is sent.

**Comment by bhavya32** [comment]
@aahnik please check issue #56 - I think you can help me out.

**Comment by aahnik** [comment]
@bhavya32 
I am currently busy with some work as I mentioned in my [previous comments](https://github.com/VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api/issues/54#issuecomment-654396506)


I have not used that part of the code so it might take time further .

# I recommend you try sending documents in a different yet SIMPLE manner

- **Upload the documents to _Google Drive_**
- **Get a Link** 
(Only the people to  whom you will give the  link can view) 
- **put the link in the message **

And it's done 😊

**Comment by aahnik** [comment]
I have made changes solving #56 and #54 part 7 solved #48 in a modular approach for send_message, send_document,send_picture
##  @bhavya32  i tried to solve your problem see my pull request #53 added new commits recently 
### do a test run 
# you can see my version of whatsapp api which i forked from @VISWESWARAN1998 [here](https://github.com/aahnik/Simple-Yet-Hackable-WhatsApp-api)
