### ISSUE TITLE
!!!UPDATE THE API!!!

### ISSUE THREAD

**Issue by t0a5ted** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#58]
most of the xpaths, selectors and classes are outdated since whatsapp's website changes every few updates. PLEASE UPDATE!!

**Comment by ashwvat** [comment]
Hey viswesh Tnx for ur update

**Comment by VISWESWARAN1998** [comment]
Thank you for using my API, I am working on the update. I have issued fixes for sending messages and pictures. I will look into other parts of the code soon.

Regards,
Visweswaran N
