### ISSUE TITLE
How to use Apache 2.0 Liscense

### ISSUE THREAD

**Issue by spfaul** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#68]
I want to refactor some of the code in this repo and use it for a personal project. I'm confused on what the Apache License requires me to do to use the code. Could someone please explain it to me?

**Comment by VISWESWARAN1998** [comment]
It is great that you are planning to personalize my project. Apache is a flexible license for personal usage, Just give attribution to the original project when required.

Thank you,
Visweswaran N

**Comment by t0a5ted** [comment]
So I just have to use the Apache 2.0 License in my own project?

Do I have to retain the following part?

`# SWAMI KARUPPASWAMI THUNNAI

# ============================================================
# Simple yet Hackable! WhatsApp API [UNOFFICIAL] for Python3
# Note: The author gives permission to use it under Apache 2.0
# Special Thanks To: alecxe, For reviewing my code!
# ============================================================
`
