### ISSUE TITLE
Installation information missing

### ISSUE THREAD

**Issue by karopass** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#9]
Hi!
I am really sorry but beginner like me can have issues in installation. I do not understood Which operating system its require to run as well How can I run this python script. I request @VISWESWARAN1998  to please add some information regarding this in wiki.
Thanks a lot :+1:

**Comment by VISWESWARAN1998** [comment]
@karopass Added it for you

**Comment by karopass** [comment]
@VISWESWARAN1998 
Thanks a lot for Quick support.
